export const ALL_ADMIN_USER_REQUEST = "ALL_ADMIN_USER_REQUEST"
export const ALL_ADMIN_USER_SUCCESS = "ALL_ADMIN_USER_SUCCESS"
export const ALL_ADMIN_USER_FAIL = "ALL_ADMIN_USER_FAIL"
export const ERROR_RESOLVE = "ALL_ERROR_RESOLVE"

export const ALL_ADMIN_ORDERS_REQUEST = "ALL_ADMIN_ORDERS_REQUEST"
export const ALL_ADMIN_ORDERS_SUCCESS = "ALL_ADMIN_ORDERS_SUCCESS"
export const ALL_ADMIN_ORDERS_FAIL = "ALL_ADMIN_ORDERS_FAIL"

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST"
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS"
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL"

export const ALL_ADMIN_USER_DELETE_REQUEST = "ALL_ADMIN_USER_DELETE_REQUEST"
export const ALL_ADMIN_USER_DELETE_SUCCESS = "ALL_ADMIN_USER_DELETE_SUCCESS"
export const ALL_ADMIN_USER_DELETE_FAIL = "ALL_ADMIN_USER_DELETE_FAIL"

export const ALL_ADMIN_ORDER_DELETE_REQUEST = "ALL_ADMIN_ORDER_DELETE_REQUEST"
export const ALL_ADMIN_ORDER_DELETE_SUCCESS = "ALL_ADMIN_ORDER_DELETE_SUCCESS"
export const ALL_ADMIN_ORDER_DELETE_FAIL = "ALL_ADMIN_ORDER_DELETE_FAIL"

export const ALL_ADMIN_USER_UPDATE_REQUEST = "ALL_ADMIN_USER_UPDATE_REQUEST"
export const ALL_ADMIN_USER_UPDATE_SUCCESS = "ALL_ADMIN_USER_UPDATE_SUCCESS"
export const ALL_ADMIN_USER_UPDATE_FAIL = "ALL_ADMIN_USER_UPDATE_FAIL"

export const ALL_ADMIN_ORDER_UPDATE_REQUEST = "ALL_ADMIN_ORDER_UPDATE_REQUEST"
export const ALL_ADMIN_ORDER_UPDATE_SUCCESS = "ALL_ADMIN_ORDER_UPDATE_SUCCESS"
export const ALL_ADMIN_ORDER_UPDATE_FAIL = "ALL_ADMIN_ORDER_UPDATE_FAIL"