export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST"
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS"
export const MY_ORDER_FAIL = "MY_ORDER_FAIL"
export const ERROR_RESOLVE = "ALL_ERROR_RESOLVE"

export const MY_ORDER_DETAIL_REQUEST = "MY_ORDER_DETAIL_REQUEST"
export const MY_ORDER_DETAIL_SUCCESS = "MY_ORDER_DETAIL_SUCCESS"
export const MY_ORDER_DETAIL_FAIL = "MY_ORDER_DETAIL_FAIL"

export const MY_PLACE_ORDER_REQUEST = "MY_PLACE_ORDER_REQUEST"
export const MY_PLACE_ORDER_SUCCESS = "MY_PLACE_ORDER_SUCCESS"
export const MY_PLACE_ORDER_FAIL = "MY_PLACE_ORDER_FAIL"

export const SPECIFIC_ORDER_DELETE_REQUEST = "SPECIFIC_ORDER_DELETE_REQUEST"
export const SPECIFIC_ORDER_DELETE_SUCCESS = "SPECIFIC_ORDER_DELETE_SUCCESS"
export const SPECIFIC_ORDER_DELETE_FAIL = "SPECIFIC_ORDER_DELETE_FAIL"