export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"
export const ERROR_RESOLVE = "ALL_ERROR_RESOLVE"

export const ALL_PRODUCTS_DETAIL_REQUEST = "ALL_PRODUCTS_DETAIL_REQUEST"
export const ALL_PRODUCTS_DETAIL_SUCCESS = "ALL_PRODUCTS_DETAIL_SUCCESS"
export const ALL_PRODUCTS_DETAIL_FAIL = "ALL_PRODUCTS_DETAIL_FAIL"

export const ALL_PRODUCTS_COMMENT_REQUEST = "ALL_PRODUCTS_COMMENT_REQUEST"
export const ALL_PRODUCTS_COMMENT_SUCCESS = "ALL_PRODUCTS_COMMENT_SUCCESS"
export const ALL_PRODUCTS_COMMENT_FAIL = "ALL_PRODUCTS_COMMENT_FAIL"