export const ALL_USERS_LOGIN_REQUEST = "ALL_USERS_LOGIN_REQUEST"
export const ALL_USERS_LOGIN_SUCCESS = "ALL_USERS_LOGIN_SUCCESS"
export const ALL_USERS_LOGIN_FAIL = "ALL_USERS_LOGIN_FAIL"
export const ERROR_RESOLVE = "ALL_ERROR_RESOLVE"

export const ALL_USERS_REGISTER_REQUEST = "ALL_USERS_REGISTER_REQUEST"
export const ALL_USERS_REGISTER_SUCCESS = "ALL_USERS_REGISTER_SUCCESS"
export const ALL_USERS_REGISTER_FAIL = "ALL_USERS_REGISTER_FAIL"

export const ALL_USERS_DETAIL_REQUEST = "ALL_USERS_DETAIL_REQUEST"
export const ALL_USERS_DETAIL_SUCCESS = "ALL_USERS_DETAIL_SUCCESS"
export const ALL_USERS_DETAIL_FAIL = "ALL_USERS_DETAIL_FAIL"